# Generated by Django 3.1.14 on 2022-03-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='final_contact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, verbose_name='Is this the final contact attempt and no other calls or home visits will be made for this participant?'),
        ),
    ]
